# Сжатие картинок с помощью SVD разложения
В этом задании нужно сделать сжатие изображения, сжатие с потерями. Для этого мы используем SVD разложение.

Примерный порядок действий:
1) Найти любую картинку,
2) Прочитать её с помощью библиотеки PIL
3) Преобразовать в numpy массив
4) Применить SVD к матрице - обязательно прочитайте справку по этой функции `np.linalg.svd`

**Примечание**: Цветная картинка представляет собой трёхканальное изображение RBG, поэтому напрямую SVD разложение применить не получится. Либо вы преобразуете изображение в одноканальное (градации серого), усредняя все три канала. Либо делаете SVD для всех трёх каналов в отдельности.

5) Далее оставляете небольшое количество сингулярных значений - 1, 2, 10, 30, 100. И выводите результат в виде получившейся картинки - чем больше сингулярных чисел, тем ближе приближённая матрица к исходной.

6) Сравните количество байт, необходимых для хранения исходной картинки и сжатой версии.

Ниже представлены основные функции и библиотеки, которые вам понадобятся.

Задание оформляете в виде блокнота jupyter. Особо понравившиеся картинки можно сохранить отдельно на диск, но мне удобнее чтобы они присутствовали в самом jupyter блокноте.

In [ ]:
from PIL import Image
import numpy as np
from matplotlib import pyplot as plt

img = Image.open('coteyka.jpg')
w, h = img.size
#img = img.resize((w//4, h//4)) # можно не делать .resize(())

# x = np.array(img, dtype=np.float32) # преобразование из PIL в numpy array
# U, S, V = np.linalg.svd(X, full_matrices=False) # разложение SVD
# # обратное преобразование из numpy array в PIL с сохранение изображения на диск
# Image.fromarray(np.asarray(Y_r, dtype=np.uint8)).save(f'{r}.png')

In [ ]:
x = np.array(img) # преобразование из PIL в numpy array


In [ ]:
x.dtype

dtype('uint8')

In [ ]:
x = np.array([1, 80, 250], dtype=np.uint8)
x

array([  1,  80, 250], dtype=uint8)

In [ ]:
x * 2

array([  2, 160, 244], dtype=uint8)

In [ ]:
x - np.array([100, 100, 100], dtype=np.uint8)

array([157, 236, 150], dtype=uint8)

In [ ]:
x = np.array(img, np.float64) # преобразование из PIL в numpy array


x.nbytes

18046560

In [ ]:
x.dtype

dtype('float64')

In [ ]:
x.shape

(820, 917, 3)

In [ ]:
U, s, Vt = np.linalg.svd(x[:,:,0], full_matrices=False) # разложение SVD
U.shape, s.shape, Vt.shape

((820, 820), (820,), (820, 917))

In [ ]:
y = U.dot(np.diag(s).dot(Vt))

In [ ]:
y.shape

(820, 917)

In [ ]:
np.allclose(x[:,:,0], y)

True

In [ ]:
r = 10
y_r = U[:, :r].dot(np.diag(s[:r]).dot(Vt[:r]))

In [ ]:
np.linalg.norm(x[:,:,0] - y_r)

np.float64(12546.938061051145)

In [ ]:
r = 1
x_new1 = x.copy()
for i in range(3):
    U, s, Vt = np.linalg.svd(x[:,:,i], full_matrices=False) # разложение SVD
    x_new1[:, :, i] = U[:, :r].dot(np.diag(s[:r]).dot(Vt[:r]))

x_new1 = np.clip(x_new1, 0, 255)
x_new1 = np.asarray(x_new1, dtype=np.uint8)
Image.fromarray(x_new1).save('coteyka1.jpg')

In [ ]:
r = 2
x_new2 = x.copy()
for i in range(3):
    U, s, Vt = np.linalg.svd(x[:,:,i], full_matrices=False) # разложение SVD
    x_new2[:, :, i] = U[:, :r].dot(np.diag(s[:r]).dot(Vt[:r]))

x_new2 = np.clip(x_new2, 0, 255)
x_new2 = np.asarray(x_new2, dtype=np.uint8)
Image.fromarray(x_new2).save('coteyka2.jpg')

In [ ]:
np.clip([0, 2, 3, 4, 5, 6], 1, 3)

array([1, 2, 3, 3, 3, 3])

In [ ]:
r = 10
x_new10 = x.copy()
for i in range(3):
    U, s, Vt = np.linalg.svd(x[:,:,i], full_matrices=False) # разложение SVD
    x_new10[:, :, i] = U[:, :r].dot(np.diag(s[:r]).dot(Vt[:r]))

x_new10 = np.clip(x_new10, 0, 255)
x_new10 = np.asarray(x_new10, dtype=np.uint8)
Image.fromarray(x_new10).save('coteyka10.jpg')

In [ ]:
r = 30
x_new30 = x.copy()
for i in range(3):
    U, s, Vt = np.linalg.svd(x[:,:,i], full_matrices=False) # разложение SVD
    x_new30[:, :, i] = U[:, :r].dot(np.diag(s[:r]).dot(Vt[:r]))

x_new30 = np.clip(x_new30, 0, 255)
x_new30 = np.asarray(x_new30, dtype=np.uint8)
Image.fromarray(x_new30).save('coteyka30.jpg')

In [ ]:
r = 100
x_new100 = x.copy()
for i in range(3):
    U, s, Vt = np.linalg.svd(x[:,:,i], full_matrices=False) # разложение SVD
    x_new100[:, :, i] = U[:, :r].dot(np.diag(s[:r]).dot(Vt[:r]))

x_new100 = np.clip(x_new100, 0, 255)
x_new100 = np.asarray(x_new100, dtype=np.uint8)
Image.fromarray(x_new100).save('coteyka100.jpg')

In [ ]:
import os
os.path.getsize("coteyka.jpg")

162905

In [ ]:
os.path.getsize("coteyka1.jpg")

31326

In [ ]:
os.path.getsize("coteyka2.jpg")

36299

In [ ]:
os.path.getsize("coteyka10.jpg")

53203

In [ ]:
os.path.getsize("coteyka30.jpg")

70978

In [ ]:
os.path.getsize("coteyka100.jpg")

87672